MessageContextErrors ResolveMessageCodes
In the MessageContextErrors.rejectValue(...) method the default message is passed into resolveMessageCodes(...) incorrectly.
The current method call is as follows:
resolveMessageCodes(errorCode, defaultMessage, field, fieldType)
The correct method call is as follows:
resolveMessageCodes(errorCode, objectName, field, fieldType)