exception on shutdown
While debugging a problem in Roo I noticed this exception on the console: 
Exception in thread "Spring Roo RooBot Add-In Index Eager Download" java.lang.NullPointerException
	at org.apache.felix.scr.impl.manager.ComponentContextImpl.getBundleContext(ComponentContextImpl.java:89)
	at org.springframework.roo.addon.roobot.client.AddOnRooBotOperationsImpl.getUpgradableBundles(AddOnRooBotOperationsImpl.java:799)
	at org.springframework.roo.addon.roobot.client.AddOnRooBotOperationsImpl.printAddonStats(AddOnRooBotOperationsImpl.java:687)
	at org.springframework.roo.addon.roobot.client.AddOnRooBotOperationsImpl.populateBundleCache(AddOnRooBotOperationsImpl.java:679)
	at org.springframework.roo.addon.roobot.client.AddOnRooBotOperationsImpl.access$100(AddOnRooBotOperationsImpl.java:59)
	at org.springframework.roo.addon.roobot.client.AddOnRooBotOperationsImpl$1.run(AddOnRooBotOperationsImpl.java:110)
	at java.lang.Thread.run(Thread.java:595)
It happens rarely when exiting the shell shortly after starting Roo and is difficult to reproduce.