Append reopen may fail
With hadoop 2.7.1 TextFileStoreAppendTests.testWriteAppendReopen fails with:






org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/TextFileStoreAppendTests/default at 0 exp: 1355388271 got: 272615628




	at org.apache.hadoop.util.DataChecksum.verifyChunkedSums(DataChecksum.java:325)




	at org.apache.hadoop.hdfs.RemoteBlockReader2.readNextPacket(RemoteBlockReader2.java:231)




	at org.apache.hadoop.hdfs.RemoteBlockReader2.read(RemoteBlockReader2.java:152)




	at org.apache.hadoop.hdfs.DFSInputStream$ByteArrayStrategy.doRead(DFSInputStream.java:737)




	at org.apache.hadoop.hdfs.DFSInputStream.readBuffer(DFSInputStream.java:793)




	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:853)




	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:896)




	at java.io.DataInputStream.read(DataInputStream.java:100)




	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:180)




	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:216)




	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)




	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:370)




	at org.springframework.data.hadoop.store.input.TextFileReader$1.doRead(TextFileReader.java:110)






It looks like closing a second append writer before read fixes this error. 