StackOverflowError when objects have cycles
The issue was first reported to Spring Integration project: https://jira.springsource.org/browse/INT-2778 and we narrowed down the problem to the fact that the persisted object had a cycle. In the reported case persisted object is Exception who&amp;apos;s default &amp;apos;cause&amp;apos; is &amp;apos;this&amp;apos; thus creating a cycle.
I think classes of type Throwable needs to be treated in a special way where instead of using Reflection getCause() should be called.
However it would also help to have some cycle detection mechanism even for the purpose of throwing a more meaningful exception (e.g., Cycle detected)